twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        post_image_dir: "%post_image_directory%"

when@test:
    twig:
        strict_variables: true
